import type { Album, MusicStreamingService } from "~/types";

export const platformAssetUrl: MusicStreamingService = {
  spotify: "spotify.webp",
  appleMusic: "apple-music.webp",
  tidal: "tidal.webp",
  jioSaavn: "jio-saavn.webp",
  youtubeMusic: "youtube-music.webp",
  amazonMusic: "amazon-music.webp",
  gaana: "gaana.webp",
  wynk: "wynk.webp",
  deezer: "deezer.webp",
  soundcloud: "soundcloud.webp",

  // Not supported yet
  napster: "napster.webp",
  reverbnation: "reverbnation.webp",
}

export const albums: Album[] = [
  {
    id: 1,
    name: "Love Proposal",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2020-05-29"),
    coverArt: "love-proposal.webp",
    urls: {
      spotify: "https://open.spotify.com/track/6poc2LV3wtr98T8NhFeols",
      appleMusic: "https://music.apple.com/in/album/love-proposal/1521871296?i=1521871297",
      tidal: "https://tidal.com/browse/track/142327977",
      youtubeMusic: "https://music.youtube.com/watch?v=8vWX3Aq7pRQ",
      amazonMusic: "https://music.amazon.in/albums/B088WTN4K1",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/love-proposal",
    },
  },
  {
    id: 2,
    name: "Game On",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2020-07-28"),
    coverArt: "game-on.webp",
    urls: {
      spotify: "https://open.spotify.com/album/1RcS75xsPj1YLlhcFje6c5",
      appleMusic: "https://music.apple.com/us/album/game-on/1523043177",
      tidal: "https://tidal.com/browse/album/296253826",
      youtubeMusic: "https://music.youtube.com/playlist?list=OLAK5uy_lF9Z_EJj-7fxk4vKB1LPCLrBrYIQf9N2c",
      amazonMusic: "https://music.amazon.in/albums/B0C5ZF9LP8",
      deezer: "https://www.deezer.com/en/album/444820265",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/sets/game-on-253652484",
    },
  },
  {
    id: 3,
    name: "Chill Out",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2020-08-26"),
    coverArt: "chill-out.webp",
    urls: {
      spotify: "https://open.spotify.com/album/2PUI3lrfX1U6BtnhjIMd57",
      appleMusic: "https://music.apple.com/in/album/chill-out/1528369083?i=1528369084",
      tidal: "https://tidal.com/browse/album/151000682",
      youtubeMusic: "https://music.youtube.com/watch?v=EOYNn4UL69A",
      amazonMusic: "https://music.amazon.in/albums/B08F9HRX1T",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/chill-out",
    },
  },
  {
    id: 4,
    name: "First crush",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2020-10-31"),
    coverArt: "first-crush.webp",
    urls: {
      spotify: "https://open.spotify.com/album/5wy8x7PEpLncFWmmglW1dz",
      appleMusic: "https://music.apple.com/in/album/first-crush/1534850753?i=1534850754",
      tidal: "https://tidal.com/browse/album/157845785",
      youtubeMusic: "https://music.youtube.com/watch?v=tkWjgBpxD8g",
      amazonMusic: "https://music.amazon.in/albums/B08KTC3GW6",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/first-crush",
    },
  },
  {
    id: 5,
    name: "Arabic Club",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2020-11-21"),
    coverArt: "arabic-club.webp",
    urls: {
      spotify: "https://open.spotify.com/album/1E9YwIV7sEAoKOxqM0ZLly",
      appleMusic: "https://music.apple.com/in/album/arabic-club/1537555513?i=1537555514",
      tidal: "https://tidal.com/browse/album/286850859",
      youtubeMusic: "https://music.youtube.com/watch?v=ELS9yRcoQC0",
      amazonMusic: "https://music.amazon.in/albums/B0C194V13G",
      deezer: "https://www.deezer.com/en/album/424840657",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/arabic-club",
    },
  },
  {
    id: 6,
    name: "Welcome To Arabia",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2020-11-24"),
    coverArt: "welcome-to-arabia.webp",
    urls: {
      spotify: "https://open.spotify.com/album/5d3DiFIxQCj9YfzY3uG9xH",
      appleMusic: "https://music.apple.com/ec/album/welcome-to-arabia-instrumental-single/1538019267",
      tidal: "https://tidal.com/browse/album/286959449",
      youtubeMusic: "https://music.youtube.com/watch?v=LMPTXLay6So",
      amazonMusic: "https://music.amazon.in/albums/B0C1C2V78F",
      deezer: "https://www.deezer.com/en/album/425065757",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/welcome-to-arabia-instrumental",
    },
  },
  {
    id: 7,
    name: "New Year 2021",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2021-02-11"),
    coverArt: "new-year-2021.webp",
    urls: {
      spotify: "https://open.spotify.com/album/30ZQWdM6SYRXXVho9EdABY",
      appleMusic: "https://music.apple.com/ec/album/new-year-2021-single/1549293184",
      tidal: "https://tidal.com/browse/album/282036283",
      youtubeMusic: "https://music.youtube.com/watch?v=qneGHdsnwj4",
      amazonMusic: "https://music.amazon.in/albums/B0BYKQWXQG",
      deezer: "https://www.deezer.com/en/album/417938697",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/new-year-2021",
    },
  },
  {
    id: 8,
    name: "Just Groove",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2021-05-28"),
    coverArt: "just-groove.webp",
    urls: {
      spotify: "https://open.spotify.com/album/3035oRIY8b8SqtIe8EG7DI",
      appleMusic: "https://music.apple.com/ec/album/just-groove-instrumental-version-single/1567359910",
      tidal: "https://tidal.com/browse/album/184017350",
      youtubeMusic: "https://music.youtube.com/watch?v=JqOdc0ddFzA",
      amazonMusic: "https://music.amazon.in/albums/B094VNQSWB",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/just-groove-instrumental",
    },
  },
  {
    id: 9,
    name: "Love Rejected",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2021-06-21"),
    coverArt: "love-rejected.webp",
    urls: {
      spotify: "https://open.spotify.com/album/6lku8X37Udp1Dlbv9voJlS",
      appleMusic: "https://music.apple.com/ec/album/love-rejected-single/1569858787",
      tidal: "https://tidal.com/browse/album/185841698",
      youtubeMusic: "https://music.youtube.com/watch?v=sNJLJYBIdOE",
      amazonMusic: "https://music.amazon.in/albums/B096482P4L",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/love-rejected",
    },
  },
  {
    id: 10,
    name: "Marne Ka Waqt Nahi",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2021-12-03"),
    coverArt: "marne-ka-waqt-nahi.webp",
    urls: {
      spotify: "https://open.spotify.com/album/4QOjHBTgyzma4AUYBhCLg4",
      appleMusic: "https://music.apple.com/ec/album/marne-ka-waqt-nahi-single/1595822678",
      tidal: "https://tidal.com/browse/album/205351123",
      youtubeMusic: "https://music.youtube.com/watch?v=QlWJfApMtM8",
      amazonMusic: "https://music.amazon.in/albums/B09LYVGX1T",
      jioSaavn: "https://www.jiosaavn.com/album/marne-ka-waqt-nahi/ZFQM36DcopE_",
      gaana: "https://gaana.com/album/marne-ka-waqt-nahi",
      wynk: "https://wynk.in/music/song/marne-ka-waqt-nahi/pp_SE6XY2180384",
      soundcloud: "https://soundcloud.com/moulibheemaneti-music/marne-ka-waqt-nahi",
    },
  },
  {
    id: 11,
    name: "A Talk With The Monster",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2022-11-02"),
    coverArt: "a-talk-with-the-monster.webp",
    urls: {
      spotify: "https://open.spotify.com/album/4WXGCC1H0YnWCLjEU1rzMl",
      appleMusic: "https://music.apple.com/us/album/a-talk-with-the-monster-single/1682312025",
      tidal: "https://tidal.com/browse/album/289060255",
      youtubeMusic: "https://music.youtube.com/watch?v=-P9t9raT-G0",
      amazonMusic: "https://music.amazon.in/albums/B0C2DK8S26",
      jioSaavn: "https://www.jiosaavn.com/album/a-talk-with-the-monster/5zApY79c8Tk_",
      deezer: "https://www.deezer.com/en/album/430065837",
    },
  },
  {
    id: 12,
    name: "MB Themes, Vol 1",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2023-07-26"),
    coverArt: "mb-themes-vol-1.webp",
    urls: {
      spotify: "https://open.spotify.com/album/3fNciXXM2LaZEQcSiz7GVj",
      appleMusic: "https://music.apple.com/us/album/mb-themes-vol-1-ep/1699024148",
      tidal: "https://tidal.com/browse/album/306915598",
      youtubeMusic: "https://music.youtube.com/playlist?list=OLAK5uy_kCgm-1xQJm_KBLux-Bp08dyC_2-ce7ABM",
      amazonMusic: "https://music.amazon.in/albums/B0CCPQ1QCH",
      jioSaavn: "https://www.jiosaavn.com/album/mb-themes-vol.-1/TP0dKIdU6QM_",
      deezer: "https://www.deezer.com/en/album/468532555",
    },
  },
  {
    id: 13,
    name: "Present Life",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2023-11-02"),
    coverArt: "present-life.webp",
    urls: {
      spotify: "https://open.spotify.com/album/7ewTnxGatCC1wQ23KBzLOw",
      appleMusic: "https://music.apple.com/us/album/present-life-single/1714187066",
      tidal: "https://tidal.com/browse/album/325211965",
      youtubeMusic: "https://music.youtube.com/watch?v=tU6fwd8w-Ho",
      amazonMusic: "https://music.amazon.in/albums/B0CM2MRFGC",
      jioSaavn: "https://www.jiosaavn.com/album/present-life/NiMk69c18X0_",
      deezer: "https://www.deezer.com/en/album/506846541",
    },
  },
  {
    id: 14,
    name: "Kushi",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2024-02-13"),
    coverArt: "kushi.webp",
    urls: {
      spotify: "https://open.spotify.com/album/4AtEUmxxhNT5yqdMVz4f3g",
      appleMusic: "https://music.apple.com/us/album/kushi/1730647414",
      tidal: "https://tidal.com/browse/album/345175041",
      youtubeMusic: "https://music.youtube.com/watch?v=70smmcYBkAg&list=OLAK5uy_mFtOcQ_QFoRd1HQIGWSOT8-iWYHpuwdn4",
      amazonMusic: "https://music.amazon.in/albums/B0CVK59PJB",
      jioSaavn: "https://www.jiosaavn.com/album/kushi/aBB0ZW9IpxA_",
      deezer: "https://www.deezer.com/en/album/547556972",
    },
  },
  {
    id: 15,
    name: "A Letter to Kushi",
    artist: "Mouli Bheemaneti",
    releaseDate: new Date("2024-06-24"),
    coverArt: "a-letter-to-kushi.webp",
    urls: {
      spotify: "https://open.spotify.com/album/1TDu8hHJur4kbs003aprOo?si=WJQf3AKMTZGjZzg2LSvA6Q",
      appleMusic: "https://music.apple.com/us/album/a-letter-to-kushi-single/1753980066",
      tidal: "https://tidal.com/browse/album/371292142",
      youtubeMusic: "https://music.youtube.com/playlist?list=OLAK5uy_kZjHmFjoJMUAgbYvs_X0xZXYlkLYXEZ6Q",
      amazonMusic: "https://music.amazon.in/albums/B0D7YPR4T8",
      jioSaavn: "https://www.jiosaavn.com/album/a-letter-to-kushi/qI4cM,hHcVA_",
      // deezer: "https://www.deezer.com/en/album/627556972",
    },
  }
]
